import JSZip from 'jszip';
import { FABRIC_TEMPLATES } from './templates';
import { GRADLEW_B64, GRADLEW_BAT_B64, GRADLE_WRAPPER_JAR_B64 } from './wrapper_binaries';

// A simple 16x16 orange square PNG for the mod icon
const DEFAULT_ICON_BASE64 = "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAIElEQVR42mP8z8BQD8SMDEwD7ICBf8D4HwZInAGDAmA0DAAA76U8v6mUeEAAAAAASUVORK5CYII=";

function base64ToUint8Array(base64: string): Uint8Array | null {
  try {
    const binaryString = atob(base64);
    const len = binaryString.length;
    const bytes = new Uint8Array(len);
    for (let i = 0; i < len; i++) {
      bytes[i] = binaryString.charCodeAt(i);
    }
    return bytes;
  } catch (e) {
    return null;
  }
}

export async function generateModZip(config: {
  modId: string;
  modName: string;
  modVersion: string;
  mavenGroup: string;
  description: string;
  extraFiles?: { path: string; content: string; encoding?: 'base64' | 'utf-8' }[];
}) {
  const zip = new JSZip();
  const { modId, modName, modVersion, mavenGroup, description, extraFiles } = config;
  const packagePath = mavenGroup.replace(/\./g, '/') + '/' + modId;

  // Root files
  zip.file('build.gradle', FABRIC_TEMPLATES.buildGradle(modId, modVersion, mavenGroup));
  zip.file('gradle.properties', FABRIC_TEMPLATES.gradleProperties(modId));
  zip.file('settings.gradle', FABRIC_TEMPLATES.settingsGradle);
  zip.file('.gitignore', ".gradle\nbuild/\nbin/\n!gradle/wrapper/gradle-wrapper.jar\n.project\n.classpath\n.settings/\n.nb-gradle/\n.vscode/\nbin/\nout/\n.DS_Store\n*.swp\n*.iml\n*.ipr\n*.iws\n.idea/\n.gradle/\nbuild/\nrun/\n");

  // Gradle wrapper
  const gradlewBytes = base64ToUint8Array(GRADLEW_B64);
  if (gradlewBytes) zip.file('gradlew', gradlewBytes, { unixPermissions: 0o755 });

  const gradlewBatBytes = base64ToUint8Array(GRADLEW_BAT_B64);
  if (gradlewBatBytes) zip.file('gradlew.bat', gradlewBatBytes);

  zip.file('gradle/wrapper/gradle-wrapper.properties', FABRIC_TEMPLATES.gradleWrapperProperties);

  const wrapperJarBytes = base64ToUint8Array(GRADLE_WRAPPER_JAR_B64);
  if (wrapperJarBytes) zip.file('gradle/wrapper/gradle-wrapper.jar', wrapperJarBytes);

  // Resources
  zip.file('src/main/resources/fabric.mod.json', FABRIC_TEMPLATES.fabricModJson(modId, modName, description, mavenGroup));
  zip.file("src/main/resources/" + modId + ".mixins.json", FABRIC_TEMPLATES.mixinJson(modId, mavenGroup));

  // Default Icon
  const iconBytes = base64ToUint8Array(DEFAULT_ICON_BASE64);
  if (iconBytes) {
    zip.file("src/main/resources/assets/" + modId + "/icon.png", iconBytes);
  }

  // Java source
  const className = modName.replace(/\s+/g, '');
  zip.file("src/main/java/" + packagePath + "/" + className + ".java", FABRIC_TEMPLATES.mainClass(modId, modName, mavenGroup));
  zip.file("src/main/java/" + packagePath + "/mixin/ExampleMixin.java", FABRIC_TEMPLATES.mixinClass(modId, mavenGroup));

  // Extra files from AI
  if (extraFiles) {
    extraFiles.forEach(file => {
      if (file.encoding === 'base64') {
        let cleanContent = file.content.trim();
        cleanContent = cleanContent.replace(/^data:image\/[a-z]+;base64,/, '');
        cleanContent = cleanContent.replace(/\s/g, '');

        const bytes = base64ToUint8Array(cleanContent);
        if (bytes) {
          zip.file(file.path, bytes);
        } else {
          console.warn(`Failed to decode base64 for ${file.path}, adding as text.`);
          zip.file(file.path, file.content);
        }
      } else {
        zip.file(file.path, file.content);
      }
    });
  }

  // Add a README with instructions
  zip.file('README.md', `# ${modName}

Generated by FabricGen for Minecraft 1.21.11.

## Setup
1. Open this folder in IntelliJ IDEA or VS Code.
2. If using IntelliJ, import as a Gradle project.
3. Run the \`genSources\` gradle task.
4. Run the \`runClient\` task to start Minecraft.

## Generated Features
${description}
`);

  return await zip.generateAsync({ type: 'blob' });
}
